Add 'make markin-shellcheck' from Wynton, but don't activate it

diff --git a/docs/Makefile.checks b/docs/Makefile.checks
--- a/docs/Makefile.checks
+++ b/docs/Makefile.checks
@@ -18,6 +18,7 @@ endif
 
 
 spell:
+	@echo "*** $@:"
 	@Rscript -e 'paths <- dir(path = c("..", "."), pattern = "*[.]md$$", full.names = TRUE, recursive = TRUE); paths <- grep("_site", paths, value = TRUE, invert = TRUE); words <- spelling::spell_check_files(paths, ignore = readLines("WORDLIST")); print(words); ok <- (nrow(words) == 0); quit(status = !ok)' || { printf "\n\nSUGGESTION: If you believe these are correctly spelled, add them to 'docs/WORDLIST'\n\n"; exit 1; }
 
 yaml-check:
@@ -191,6 +192,35 @@ check-leftovers:
 	  exit 1
 	fi
 
+markin-shellcheck:
+	@stdout=$(TMPDIR)/stdout
+
+	ok_count=0
+	error_count=0
+	config=.markdown-link-check.json
+
+	echo "*** $@:"
+	files=$$(find . -type f -name "*.sh" -not -path "./_site/*")
+	for file in $$files; do
+	   $(TPUT) && printf "[    ] checking %s" "$$file"
+	   if shellcheck -x "$$file" &>> "$$stdout" ; then
+	     ok_count=$$((ok_count+1))
+	     $(TPUT) && printf "\r"
+	     printf "[$(OK)] checking %s\\n" "$$file"
+	   else
+	     error_count=$$((error_count+1))
+	     $(TPUT) && printf "\r"
+	     printf "[$(FAIL)] checking %s\\n" "$$file"
+	   fi
+	done
+
+	echo "RESULT: $$ok_count OK, $$error_count ERROR"
+	if (( error_count > 0 )); then
+	  grep -B 1 -E "(^ERROR:|^\[(✖|x)\]|Status: [0-9]+$$)" "$$stdout"
+	  cat "$$stdout"
+	  exit 1
+	fi
+
 check-markdown: markdownlint markdown-link-check
 
-check: check-here-links check-usernames check-leftovers spell check-markdown
+check: check-here-links check-usernames spell check-markdown check-leftovers 
