Add 'make check-usernames' to assert that personal usernames are included in examples and code snippets

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -155,6 +155,35 @@ markdown-link-check:
 	  exit 1
 	fi
 
-check: spell markdownlint markdown-link-check
+check-usernames:
+	@stdout=$(TMPDIR)/stdout
+
+	ok_count=0
+	error_count=0
+	config=.markdown-link-check.json
+
+	files=$$(find . -type f -name "*.md" -not -path "./_site/*")
+	for file in $$files; do
+	   $(TPUT) && printf "[    ] checking %s" "$$file"
+	   if ! grep -H -n -E "\b(hb|hb-test|henrik|hhputnam)\b" "$$file" &>> "$$stdout" ; then
+	     ok_count=$$((ok_count+1))
+	     $(TPUT) && printf "\r"
+	     printf "[$(OK)] checking %s\\n" "$$file"
+	   else
+	     error_count=$$((error_count+1))
+	     $(TPUT) && printf "\r"
+	     printf "[$(FAIL)] checking %s\\n" "$$file"
+	   fi
+	done
+
+	echo "RESULT: $$ok_count OK, $$error_count ERROR"
+	if (( error_count > 0 )); then
+	  grep -B 1 -E "(^ERROR:|^\[(✖|x)\]|Status: [0-9]+$$)" "$$stdout"
+	  echo "$$stdout"
+	  cat "$$stdout"
+	  exit 1
+	fi
+
+check: spell markdownlint markdown-link-check check-usernames
 
 FORCE:
